### ISSUE TITLE
Write User-space Go for biscuit

### ISSUE THREAD

**Issue by borats** [mit-pdos/biscuit#9]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
```
go version go1.10.3 linux/amd64
```

### Does this issue reproduce with the latest release?
N/A

### What operating system and processor architecture are you using (`go env`)?
```
GOOS="linux"
GOARCH="amd64"
```

### What did you do?
N/A

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

### What did you expect to see?
That I am able to run Go binaries in biscuit

### What did you see instead?
N/A

Are there any support in biscuit to run user-space Go binaries? I see C++ and C (e.g. `user/c/lsh.c`) but no Go. Where do I start?

**Comment by grodranlorth** [comment]
Biscuit does not currently support running Go binaries in user-space.

However, Biscuit does support the system calls most commonly used by the Go runtime (exit, write, usleep, nanotime, mmap, munmap, futex, and clone), so it probably wouldn't take much work to get user-space Go working.

**Comment by grodranlorth** [comment]
I'm afraid not.

**Comment by borats** [comment]
> I'm afraid not.

No problem. Thanks for the clarification.
